version: 2
updates:
  # Verifica dependências do projeto
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    target-branch: "development"
    open-pull-requests-limit: 10