name: 'Automatic create tag version'

on:
  push:
    branches:
      - main
      - development

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  automatic-create-tag:
    uses: oisamitech/api-action-core/.github/workflows/tag-version-workflow.yml@main
    secrets:
      pat_token: ${{ secrets.AUTOMATION }}
